[package]
name = "tinyDB"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
tokio = { version = "1.24.2", features=["full","tracing"]}
tokio-stream = {version="0.1.11"}
tokio-util = {version="0.7.4",features=["full"]}
